version: '3.8'

services:
  chroma:
    image: chromadb/chroma:latest
    container_name: library-mvp-chroma
    environment:
      - ALLOW_RESET=false  # Disable reset in production
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_AUTH_USERNAME}:${CHROMA_AUTH_PASSWORD}
      - CHROMA_SERVER_AUTH_CREDENTIALS_FILE=/chroma/auth/credentials.txt
      - CHROMA_SERVER_AUTH_PROVIDER=basic
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT=header
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=${CHROMA_CORS_ORIGINS}
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_HTTP_TIMEOUT=30
      - CHROMA_SERVER_MAX_CONNECTIONS=100
    volumes:
      - chroma_data:/chroma/chroma
      - ./auth:/chroma/auth
    expose:
      - "8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
      - no-exec:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: library-mvp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - chroma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
    driver: local 